version: '3.7'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "shedlock_sample"
      POSTGRES_PASSWORD: "Welcome123"
      POSTGRES_DB:       "shedlock"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  schedlock:
    image: schedlock/schedlock:0.0.1-SNAPSHOT
    networks:
      backend:
        aliases:
          - "schedlock"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/shedlock
    deploy:
      replicas: 3

networks:
  backend:
    driver: overlay 
